### ISSUE TITLE
Question: How should our meta-primitives behave?

### ISSUE THREAD

**Issue by schroedingerscode** [PegaSysEng/artemis#100]
### Description
How primitive should our meta-primitives be?

### Additional Information
Should our "primitives" i.e. UInt64 behave like traditional unsigned primitives in other languages, and allow the programmer to (un)intentionally underflow/overflow, or should an exception be thrown if underflow/overflow is detected?

**Comment by jrhea** [comment]
@schroedingerscode is this still an open question?

**Comment by schroedingerscode** [comment]
While the example is no longer applicable because we're accepting the default Guava UnsignedLong behavior, I think it is still important for the handful of other primitives in the Eth2 spec.

I'm of the opinion a primitive should behave like a primitive and protection is the job of the calling function. Separation of responsibilities and such. But I would still like others' opinions.

**Comment by schroedingerscode** [comment]
I think we've reached sufficient internal consensus on this, especially given significant bounds checking will be necessary when using Guava's UnsignedLong anyway, that primitives will be primitives. Bounds checking is up to the user of the primitives.
