### ISSUE TITLE
Support UInt types in Java

### ISSUE THREAD

**Issue by akhila-raju** [PegaSysEng/artemis#22]
Support Uint16, Uint24, Uint64, Uint256, Uint384 types.

**Comment by jrhea** [comment]
@schroedingerscode & @akhila-raju  is this resolved?

**Comment by schroedingerscode** [comment]
@jrhea I do believe this is resolved. The spec has evolved so fast, some of those are unnecessary. I think it probably makes the most sense to use ints and longs where they make sense, and then implement UInt384/Bytes48 as described in #68 for containing the BLS sigs.

**Comment by akhila-raju** [comment]
Agreed.
