### ISSUE TITLE
Support YAML parsing for Eth2.0 tests

### ISSUE THREAD

**Issue by akhila-raju** [PegaSysEng/artemis#23]
https://github.com/ethereum/eth2.0-specs/blob/master/specs/test-format.md

**Comment by schroedingerscode** [comment]
https://github.com/ConsenSys/cava/pull/169 implements some of this functionality within Cava to run the Eth2 SSZ tests. I believe we should run them independently against our own data types in Artemis, and that it would be prudent to add https://github.com/ethereum/eth2.0-tests as a submodule in our own project so our client is tested against the reference tests as well. This PR is therefore being left open to track that work.
