### ISSUE TITLE
Implement SSZ

### ISSUE THREAD

**Issue by dangerousfood** [PegaSysEng/artemis#28]
Implement SSZ in accordance with the spec listed [here](https://github.com/ethereum/beacon_chain/tree/master/ssz). Additional resources can be found here [here](https://github.com/ethereum/eth2.0-specs/issues/129)

**Comment by jrhea** [comment]
@dangerousfood What is the status of this?  Do you have an implementation in Java, or are you going to use Antoine's version in Cava?

**Comment by atoulme** [comment]
tagging myself @atoulme so I get notified of updates.

**Comment by jrhea** [comment]
@atoulme you finished the implementation in cava, right?

**Comment by atoulme** [comment]
I would have to look again. The spec changed a bit since. I was unsure if we needed a special construct to handle containers. There were changes related to endianness. I also had left out the hashing.

**Comment by jrhea** [comment]
Just glanced at the cava source and it looks like one potential issue with using the cava SSZ implementation is:

import net.consensys.cava.bytes.Bytes;
import net.consensys.cava.units.bigints.UInt256;

We have different types in Artemis.

**Comment by atoulme** [comment]
What types do you folks need? Bytes is just an array of bytes with better methods.

FWIW Harmony is using Cava SSZ: https://github.com/harmony-dev/beacon-chain-java/blob/master/ssz/src/main/java/net/consensys/cava/ssz/BytesSSZReaderProxy.java

**Comment by atoulme** [comment]
This PR should help: https://github.com/PegaSysEng/artemis/pull/207

**Comment by atoulme** [comment]
PR #208 brings SSZ to the project.

**Comment by jrhea** [comment]
resolved by #208
