### ISSUE TITLE
Something is causing the build to fail

### ISSUE THREAD

**Issue by jrhea** [PegaSysEng/artemis#32]
### Description
There is something causing the build to stall not complete. (circular reference?)

### Acceptance Criteria
* bytes and uint need to belong to the same package

### Steps to Reproduce (Bug)
1. ./gradlew clean build test

> Never completes.  It just hangs

**Comment by schroedingerscode** [comment]
Adding to the mystery, I ran a git bisect, and it looks like f453180354ee903a078758e5cf9bec1aabb2ad91 is the first bad commit. No clue why that's causing gradle to lock up, but that's a task for tomorrow.
