### ISSUE TITLE
Create initial ChainStoreService

### ISSUE THREAD

**Issue by jrhea** [PegaSysEng/artemis#80]
Create ChainStoreService.java:
- stores blocks, attestations, and states
- controls what to keep in memory and what to write to disk

> Note: Alway worth looking at what Pantheon did:
> https://github.com/PegaSysEng/pantheon/tree/master/services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore

**Comment by schroedingerscode** [comment]
🚧 **This enhancement is in progress.** 🚧
See https://github.com/PegaSysEng/artemis/compare/master...schroedingerscode:feat/chain-store-service to stay up to date with the changes being made.

**Current Status:** Scaffolding for new service has been created and is building.

**Comment by jrhea** [comment]
closed by #228
