### ISSUE TITLE
Automate testing of the ValidatorRegistrationContract.java and ValidatorRegistrationClient.java

### ISSUE THREAD

**Issue by dangerousfood** [PegaSysEng/artemis#93]
Utilize the framework laid out in Issue #46 to automate the testing of ValidatorRegistrationContract.java and ValidatorRegistrationClient.java. Ensuring the firing of the events Eth1Deposit and ChainStart are critical to triggering the BeaconChain.

**Comment by akhila-raju** [comment]
@dangerousfood, has this been completed or is it still an open issue?
