### ISSUE TITLE
Automate debug mode for PoW chain

### ISSUE THREAD

**Issue by dangerousfood** [PegaSysEng/artemis#94]
If the debug flag is set to true in the pow/config.properties file.

- [x] Gradle instantiates an instance ganache-cli 

- [x] Deploy PoW chain contracts

- [x] Generate 2^14 (16384) accounts with 100 ETH each

- [x] Provide the credentials to the accounts to pow module at runtime

**Comment by akhila-raju** [comment]
@dangerousfood, has this been completed or is it still an open issue?

**Comment by dangerousfood** [comment]
Open issue. I covered two of these items in another PR. There are still two outstanding.
