### ISSUE TITLE
Automate auto-generation of ValidatorRegistrationContract.java in gradle

### ISSUE THREAD

**Issue by dangerousfood** [PegaSysEng/artemis#99]
Gradle should automate the code auto-generation of ValidatorRegistrationContract.java from the vrc.v.py Vyper contract. Currently, Vyper is unsupported by web3j for automated code-generation. That is the reason for having the scaffolding contract vrc.sol.

Implementer must automate a way to use the Vyper environment to build the ABI and BIN for the vrc.v.py contract. The ABI and BIN can then be used for auto-generating the ValidatorRegistrationContract.java class.

**Comment by akhila-raju** [comment]
@dangerousfood, is this still in progress? I see that the issue in web3j is still open.
